// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
/// IMPORTANT: Replace these placeholder values with your actual Firebase project configuration
/// Run `flutterfire configure` to generate the correct values automatically
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvgSB62sB9py6zDc0yGGPcykAkuV7ni14',
    appId: '1:166079306239:web:c80c1ab5982156c6e26fca',
    messagingSenderId: '166079306239',
    projectId: 'mobileapp-1e7ea',
    authDomain: 'mobileapp-1e7ea.firebaseapp.com',
    storageBucket: 'mobileapp-1e7ea.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvgSB62sB9py6zDc0yGGPcykAkuV7ni14',
    appId: '1:166079306239:android:c80c1ab5982156c6e26fca',
    messagingSenderId: '166079306239',
    projectId: 'mobileapp-1e7ea',
    storageBucket: 'mobileapp-1e7ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvgSB62sB9py6zDc0yGGPcykAkuV7ni14',
    appId: '1:166079306239:ios:c80c1ab5982156c6e26fca',
    messagingSenderId: '166079306239',
    projectId: 'mobileapp-1e7ea',
    storageBucket: 'mobileapp-1e7ea.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvgSB62sB9py6zDc0yGGPcykAkuV7ni14',
    appId: '1:166079306239:ios:c80c1ab5982156c6e26fca',
    messagingSenderId: '166079306239',
    projectId: 'mobileapp-1e7ea',
    storageBucket: 'mobileapp-1e7ea.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvgSB62sB9py6zDc0yGGPcykAkuV7ni14',
    appId: '1:166079306239:web:c80c1ab5982156c6e26fca',
    messagingSenderId: '166079306239',
    projectId: 'mobileapp-1e7ea',
    authDomain: 'mobileapp-1e7ea.firebaseapp.com',
    storageBucket: 'mobileapp-1e7ea.firebasestorage.app',
  );
}
